// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 110 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int storing_dataparameter_110 = 110;
	/// <summary>PID: 110 | Type: read</summary>
	public const int storing_dataparameter = 110;
	public class Write
	{
		/// <summary>PID: 101 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int storing_button_qa101_101 = 101;
		/// <summary>PID: 101 | Type: write</summary>
		public const int storing_button_qa101 = 101;
		/// <summary>PID: 102 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int storing_button_qa102_102 = 102;
		/// <summary>PID: 102 | Type: write</summary>
		public const int storing_button_qa102 = 102;
		/// <summary>PID: 201 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int caching_button_201 = 201;
		/// <summary>PID: 201 | Type: write</summary>
		public const int caching_button = 201;
		/// <summary>PID: 301 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sharing_button_qa301_301 = 301;
		/// <summary>PID: 301 | Type: write</summary>
		public const int sharing_button_qa301 = 301;
		/// <summary>PID: 302 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sharing_button_qa302_302 = 302;
		/// <summary>PID: 302 | Type: write</summary>
		public const int sharing_button_qa302 = 302;
	}
}
public class WriteParameters
{
	/// <summary>PID: 101  | Type: write | DISCREETS: Storing - QA101 = 1</summary>
	public System.Object Storing_button_qa101 {get { return Protocol.GetParameter(101); }set { Protocol.SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: write | DISCREETS: Storing - QA102 = 1</summary>
	public System.Object Storing_button_qa102 {get { return Protocol.GetParameter(102); }set { Protocol.SetParameter(102, value); }}
	/// <summary>PID: 201  | Type: write | DISCREETS: Caching = 1</summary>
	public System.Object Caching_button {get { return Protocol.GetParameter(201); }set { Protocol.SetParameter(201, value); }}
	/// <summary>PID: 301  | Type: write | DISCREETS: Sharing - QA301 = 1</summary>
	public System.Object Sharing_button_qa301 {get { return Protocol.GetParameter(301); }set { Protocol.SetParameter(301, value); }}
	/// <summary>PID: 302  | Type: write | DISCREETS: Sharing - QA302 = 1</summary>
	public System.Object Sharing_button_qa302 {get { return Protocol.GetParameter(302); }set { Protocol.SetParameter(302, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Storing_title_begin__fixed { get; set; }
	object Storing_button_qa101_101 { get; set; }
	object Storing_button_qa101 { get; set; }
	object Storing_button_qa102_102 { get; set; }
	object Storing_button_qa102 { get; set; }
	object Storing_dataparameter_110 { get; set; }
	object Storing_dataparameter { get; set; }
	object Caching_title_begin__fixed { get; set; }
	object Caching_button_201 { get; set; }
	object Caching_button { get; set; }
	object Sharing_title_begin__fixed { get; set; }
	object Sharing_button_qa301_301 { get; set; }
	object Sharing_button_qa301 { get; set; }
	object Sharing_button_qa302_302 { get; set; }
	object Sharing_button_qa302 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 100  | Type: fixed</summary>
	public System.Object Storing_title_begin__fixed {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 101  | Type: write | DISCREETS: Storing - QA101 = 1</summary>
	public System.Object Storing_button_qa101_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: write | DISCREETS: Storing - QA101 = 1</summary>
	public System.Object Storing_button_qa101 {get { return Write.Storing_button_qa101; }set { Write.Storing_button_qa101 = value; }}
	/// <summary>PID: 102  | Type: write | DISCREETS: Storing - QA102 = 1</summary>
	public System.Object Storing_button_qa102_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: write | DISCREETS: Storing - QA102 = 1</summary>
	public System.Object Storing_button_qa102 {get { return Write.Storing_button_qa102; }set { Write.Storing_button_qa102 = value; }}
	/// <summary>PID: 110  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Storing_dataparameter_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 110  | Type: read</summary>
	public System.Object Storing_dataparameter {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 200  | Type: fixed</summary>
	public System.Object Caching_title_begin__fixed {get { return GetParameter(200); }set { SetParameter(200, value); }}
	/// <summary>PID: 201  | Type: write | DISCREETS: Caching = 1</summary>
	public System.Object Caching_button_201 {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 201  | Type: write | DISCREETS: Caching = 1</summary>
	public System.Object Caching_button {get { return Write.Caching_button; }set { Write.Caching_button = value; }}
	/// <summary>PID: 300  | Type: fixed</summary>
	public System.Object Sharing_title_begin__fixed {get { return GetParameter(300); }set { SetParameter(300, value); }}
	/// <summary>PID: 301  | Type: write | DISCREETS: Sharing - QA301 = 1</summary>
	public System.Object Sharing_button_qa301_301 {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 301  | Type: write | DISCREETS: Sharing - QA301 = 1</summary>
	public System.Object Sharing_button_qa301 {get { return Write.Sharing_button_qa301; }set { Write.Sharing_button_qa301 = value; }}
	/// <summary>PID: 302  | Type: write | DISCREETS: Sharing - QA302 = 1</summary>
	public System.Object Sharing_button_qa302_302 {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 302  | Type: write | DISCREETS: Sharing - QA302 = 1</summary>
	public System.Object Sharing_button_qa302 {get { return Write.Sharing_button_qa302; }set { Write.Sharing_button_qa302 = value; }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
